# Feature Pyramid Network (FPN) configuration
#
# Standard FPN with 256 output channels

type: FPN
in_channels: [96, 192, 384, 768]  # Swin Tiny output channels
out_channels: 256
num_outs: 5
start_level: 0
end_level: -1
add_extra_convs: on_input
relu_before_extra_convs: false
