# RTMDet-M (COCO)

preset_meta:
  aliases: [rtmdet-m]
  weights: https://download.openmmlab.com/mmdetection/v3.0/rtmdet/rtmdet_m_8xb32-300e_coco/rtmdet_m_8xb32-300e_coco_20220719_112220-229f527c.pth

_base_: ./rtmdet_l.yaml

backbone:
  deepen_factor: 0.67
  widen_factor: 0.75

neck:
  in_channels: [192, 384, 768]
  out_channels: 192
  num_csp_blocks: 2

bbox_head:
  in_channels: 192
  feat_channels: 192
