# RTMDet-Ins-X (COCO)

_base_: ./rtmdet_ins_l.yaml

backbone:
  deepen_factor: 1.33
  widen_factor: 1.25

neck:
  in_channels: [320, 640, 1280]
  out_channels: 320
  num_csp_blocks: 4

bbox_head:
  in_channels: 320
  feat_channels: 320
