# RTMDet-Ins-X (COCO)

preset_meta:
  aliases: [rtmdet-ins-x]
  weights: https://download.openmmlab.com/mmdetection/v3.0/rtmdet/rtmdet-ins_x_8xb16-300e_coco/rtmdet-ins_x_8xb16-300e_coco_20221124_111313-33d4595b.pth

_base_: ./rtmdet_ins_l.yaml

backbone:
  deepen_factor: 1.33
  widen_factor: 1.25

neck:
  in_channels: [320, 640, 1280]
  out_channels: 320
  num_csp_blocks: 4

bbox_head:
  in_channels: 320
  feat_channels: 320
