# RTMDet-S (COCO)

preset_meta:
  aliases: [rtmdet-s]
  weights: https://download.openmmlab.com/mmdetection/v3.0/rtmdet/rtmdet_s_8xb32-300e_coco/rtmdet_s_8xb32-300e_coco_20220905_161602-387a891e.pth

_base_: ./rtmdet_l.yaml

backbone:
  deepen_factor: 0.33
  widen_factor: 0.5

neck:
  in_channels: [128, 256, 512]
  out_channels: 128
  num_csp_blocks: 1

bbox_head:
  in_channels: 128
  feat_channels: 128
  exp_on_reg: false
