# RTMDet-Ins-S (COCO)

_base_: ./rtmdet_ins_l.yaml

backbone:
  deepen_factor: 0.33
  widen_factor: 0.5

neck:
  in_channels: [128, 256, 512]
  out_channels: 128
  num_csp_blocks: 1

bbox_head:
  in_channels: 128
  feat_channels: 128
