# RTMDet-Ins-M (COCO)

_base_: ./rtmdet_ins_l.yaml

backbone:
  deepen_factor: 0.67
  widen_factor: 0.75

neck:
  in_channels: [192, 384, 768]
  out_channels: 192
  num_csp_blocks: 2

bbox_head:
  in_channels: 192
  feat_channels: 192
